apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.postgresql.DB_PASSWORD | b64enc }} 